name: changelog

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  cliffy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make CHANGELOG.md
      - uses: peter-evans/create-pull-request@v7
        with:
          branch: cliffy/changelog
          add-paths: CHANGELOG.md
          commit-message: "doc(changelog): Update CHANGELOG.md"
          title: "doc(changelog): Update CHANGELOG.md"
          body: |
            **[Preview](https://github.com/square/exoskeleton/blob/cliffy/changelog/CHANGELOG.md)**
