name: changelog

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  cliffy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make CHANGELOG.md
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "doc(changelog): Update CHANGELOG.md"
