#!/usr/bin/env bash
# SUMMARY: List directory contents
# HELP: USAGE
#    ls [FILE]...
#
# DESCRIPTION
#    For each operand that names a file of a type other than directory,
#    ls displays its name as well as any requested, associated information.
#
#    For each operand that names a file of type directory, ls displays
#    the names of files contained within that directory, as well as any
#    requested, associated information.

ls "$@"
