#!/usr/bin/env bash
# SUMMARY: Remove directory entries
# HELP: USAGE
#    rm [FILE]...
#
# DESCRIPTION
#    The rm utility attempts to remove the non-directory type files
#    specified on the command line. If the permissions of the file do not
#    permit writing, and the standard input device is a terminal,
#    the user is prompted (on the standard error output) for confirmation.

rm "$@"
